on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: [ 'petclinic/**' ]
  pull_request:
    branches: [master]
    paths: [ 'petclinic/**' ]

jobs:
  cicd-application:
    name: Execute AWS CodePipeline
    runs-on: ubuntu-latest
    environment: Demo
    steps:
      - uses: actions/checkout@v3
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        if: github.ref == 'refs/heads/master'
        with:
          aws-region: "eu-west-1"
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          pipeline-name: "petclinic-master-Pipeline"